// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvqgdppbfikhcbwgkskx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12cWdkcHBiZmlraGNid2drc2t4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2ODAwMTEsImV4cCI6MjA1ODI1NjAxMX0.KABeGhRwaWsqoQbymXwy_wONZnOa2P_BTcNMeP_fPiU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);